create table if not exists public.message_send_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  exam_id text,
  exam_name text not null default '',
  student_id text,
  student_name text not null default '',
  group_label text not null default '',
  recipient_last4 text not null default '',
  provider text not null default 'solapi',
  status text not null check (status in ('requested','failed','delivered','undelivered')),
  provider_reference text,
  error_message text
);

create index if not exists message_send_logs_created_at_idx
  on public.message_send_logs (created_at desc);

alter table public.message_send_logs enable row level security;

drop policy if exists message_send_logs_read on public.message_send_logs;
create policy message_send_logs_read on public.message_send_logs
  for select to anon, authenticated using (true);

drop policy if exists message_send_logs_insert on public.message_send_logs;
create policy message_send_logs_insert on public.message_send_logs
  for insert to anon, authenticated with check (
    provider = 'solapi'
    and status in ('requested','failed','delivered','undelivered')
    and recipient_last4 ~ '^[0-9]{4}$'
  );

grant select, insert on public.message_send_logs to anon, authenticated;
grant usage, select on sequence public.message_send_logs_id_seq to anon, authenticated;
