'use strict';
const $=id=>document.getElementById(id), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), N=n=>Number(n||0).toLocaleString('ko-KR');
const token=document.querySelector('meta[name="research-token"]').content;
let page='home',summary=null,students=[],schools=[],sid='',currentAnalysis=null,offset=0,bankQuery='',bankStatus='',bankSource='',selected=[],charts=[],toastTimer;
const titles={home:'연구실 홈',students:'학생 오답 분석',bank:'문제은행',sources:'원본 · 프린트 근거',daily:'오늘의 복습',packets:'개인별 자료'};
async function api(path,data){if(window.researchAPI)return window.researchAPI(path,data);const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Research-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'처리하지 못했습니다.');return v;}
function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,8000);}
async function action(fn,button){if(button)button.disabled=true;try{return await fn();}catch(e){toast(e.message);return null;}finally{if(button?.isConnected)button.disabled=false;}}
function on(id,fn){if($(id))$(id).onclick=e=>action(()=>fn(e),e.currentTarget);}
function modal(title,body){$('dialog-title').textContent=title;$('dialog-body').innerHTML=body;if(!$('dialog').open)$('dialog').showModal();}
function empty(title,description=''){return `<div class="empty"><strong>${E(title)}</strong>${E(description)}</div>`;}
function badge(text,color=''){return `<span class="badge ${color}">${E(text)}</span>`;}
function heading(title,desc,extra=''){return `<div class="heading"><div><p class="eyebrow">ODAP RESEARCH LAB</p><h1>${E(title)}</h1><p>${E(desc)}</p></div>${extra}</div>`;}
function stats(items){return '<div class="stats">'+items.map(([label,value,unit,note,icon])=>`<div class="stat"><span class="stat-icon">${icon||'◫'}</span><div class="stat-label">${E(label)}</div><div class="stat-value">${N(value)}<em>${E(unit)}</em></div><small>${E(note)}</small></div>`).join('')+'</div>';}
function sourceOptions(selectedId=''){return (summary?.sources||[]).map(s=>`<option value="${E(s.id)}" ${s.id===selectedId?'selected':''}>${E(s.title)}</option>`).join('');}
async function getStudents(){if(!students.length){const r=await api('/api/students');students=r.students;schools=r.schools;}return students;}
function studentName(){return students.find(s=>String(s.id)===sid)?.name||'학생';}
function studentPicker(){return `<label>김까까 학생<select id="student-picker"><option value="">학생을 선택하세요</option>${students.map(s=>`<option value="${E(s.id)}" ${String(s.id)===sid?'selected':''}>${E(s.name)} · ${E(schools.find(x=>String(x.id)===String(s.school_id))?.name||s.id)}</option>`).join('')}</select></label>`;}
function wireStudent(){if($('student-picker'))$('student-picker').onchange=()=>{sid=$('student-picker').value;selected=[];action(()=>navigate(page));};}
function questionImagesMarkup(images){return '<div class="question-images">'+(images||[]).filter(x=>/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(x.data||'')).map(x=>`<img src="${x.data}" alt="${E(x.alt||'원본 지면')}">`).join('')+'</div>';}
function questionMarkup(q,answers=true){return `<div class="question-text">${E(q.text)}</div>${q.passage?`<div class="passage">${E(q.passage)}</div>`:''}<div class="question-images">${(q.images||[]).filter(x=>/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(x.data||'')).map(x=>`<img src="${x.data}" alt="${E(x.alt||'원본 그림')}">`).join('')}</div>${q.choices?.length?'<ol class="question-choices">'+q.choices.map(x=>`<li>${E(x)}</li>`).join('')+'</ol>':''}${answers?`<p><strong>정답 ${E(q.answer||'미확인')}</strong></p><div class="passage">${E(q.explanation||'해설 미확인')}</div>${questionImagesMarkup(q.explanation_images)}`:''}`;}
async function navigate(name){page=name;charts.forEach(c=>c.destroy());charts=[];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$('breadcrumb').textContent=titles[name];$('main').innerHTML='<div class="loading">실제 저장 기록을 불러오고 있습니다…</div>';try{await ({home:home,students:studentPage,bank:bankPage,sources:sourcePage,daily:dailyPage,packets:packetPage}[name])();}catch(e){$('main').innerHTML=heading(titles[name],'연결 상태를 확인해 주세요')+empty('불러오지 못했습니다',e.message);toast(e.message);} }
async function home(){summary=await api('/api/summary');const t=summary.totals,c=summary.connection;
 $('nav-count').textContent=N(t.questions);
 $('main').innerHTML=heading('오답이 다음 배움의 시작이 되도록','학생의 기록과 원문 근거를 함께 살피는 선생님의 연구실',`<span class="today">${new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'})}</span>`)+
 stats([['김까까 학생',c.students,'명','기존 학생 DB 직접 연결','◎'],['저장된 문항 후보',t.questions,'문항','실제 문제은행 DB 적재 건수','▤'],['검수 완료',t.approved,'문항','교사가 확인한 정답·해설·개념','✓'],['생성문항 검토',t.pending_generated,'문항','승인 전 학생에게 공개되지 않음','✧']])+
 `<div class="hero"><div><p class="eyebrow">TODAY’S WORKSPACE</p><h2>원문을 확인하고, 필요한 복습을 골라 주세요.</h2><p>학생 선택 → 오답과 근거 확인 → 맞춤 자료 제작</p></div><button class="primary" id="go-students">학생 오답 살펴보기 →</button></div>`+
 `<div class="grid"><div><section class="card"><div class="card-head"><h2>자료 적재 현황</h2><button id="go-sources" class="subtle">전체 ${N(t.sources)}개 원본 ↗</button></div><div class="notice"><strong>파일 보관과 문항 검수는 서로 다릅니다.</strong>문항 후보 ${N(t.questions)}개 중 ${N(t.approved)}개를 검수했습니다. 추출한 표·그림·정답은 원본과 대조해야 합니다.</div><div class="table-wrap"><table><thead><tr><th>원본 자료</th><th>적재</th><th>검수</th><th>상태</th></tr></thead><tbody>${summary.sources.slice(0,7).map(s=>`<tr><td class="source-title">${E(s.title)}</td><td>${N(s.total)}</td><td>${N(s.approved)}</td><td>${badge(s.approved===s.total&&s.total?'검수 완료':'검토 대기',s.approved===s.total&&s.total?'green':'amber')}</td></tr>`).join('')}</tbody></table></div></section></div><div><section class="card"><div class="card-head"><h2>김까까 연결</h2>${badge(c.ok?'연결됨':'연결 확인',c.ok?'green':'red')}</div><div class="source-row"><span>학생 · 기존 ID 사용</span><b>${N(c.students)}명</b></div><div class="source-row"><span>시험·과제</span><b>${N(c.exams)}개</b></div><div class="source-row"><span>제출 기록</span><b>${N(c.responses)}건</b></div><p class="mini-stat">${E(c.checked_at||c.error)}</p>${!c.has_student_id?'<p class="notice">학생 계정은 정상적으로 있습니다. 이전 제출은 이름만 저장돼 있어, 학생 분석에서 본인 기록을 확인해 기존 ID에 연결해야 합니다.</p>':''}</section><section class="card"><h2>연구실 이용 순서</h2><ol class="help-list"><li>기존 학생과 제출 기록의 연결을 확인합니다.</li><li>원문 문항을 검수하고 세부 개념을 붙입니다.</li><li>프린트 페이지·근거·핵심명제를 연결합니다.</li><li>복습문항과 개인별 자료를 검토해 승인합니다.</li></ol><button id="go-bank">문제은행 검수 시작 →</button></section></div></div>`;
 on('go-students',()=>navigate('students'));on('go-bank',()=>navigate('bank'));on('go-sources',()=>navigate('sources'));
}
async function bankPage(){if(!summary)summary=await api('/api/summary');const r=await api('/api/questions?'+new URLSearchParams({q:bankQuery,status:bankStatus,source_id:bankSource,offset}));
 $('main').innerHTML=heading('문제은행','원문·정답·해설을 확인하고, 학생에게 필요한 문항을 찾아보세요.',badge(`${N(r.total)}문항`,'green'))+
 `<section class="card"><form id="bank-search" class="filters"><label class="wide">통합 검색<input id="search" value="${E(bankQuery)}" placeholder="발문, 개념, 출처, 학교 검색"></label><label>검수 상태<select id="status"><option value="">전체</option value="pending" ${bankStatus==='pending'?'selected':''}>미검수 후보</option><option value="approved" ${bankStatus==='approved'?'selected':''}>검수 완료</option></select></label><label>원본 자료<select id="source"><option value="">전체 원본</option>${sourceOptions(bankSource)}</select></label><button class="primary">검색</button></form><div class="table-wrap"><table><thead><tr><th style="width:55%">문항 · 출처</th><th>개념</th><th>검수</th><th></th></tr></thead><tbody>${r.items.map(q=>`<tr><td><div class="source-title">${E(q.text)}</div><small>${E(q.source_title)} · ${E(q.original_number)}번</small></td><td>${E((q.concepts||[]).join(' · ')||q.classification_hint||'미분류')}<br>${!q.concepts?.length?'<small>원본 분류 힌트 · 미확정</small>':''}</td><td>${badge(q.reviewed?'검수 완료':'미검수',q.reviewed?'green':'amber')}</td><td><button data-question="${E(q.id)}">검토·수정</button></td></tr>`).join('')}</tbody></table></div>${!r.items.length?empty('검색 결과가 없습니다','다른 검색어나 원본을 선택하세요.'):''}<div class="pagination"><span>${N(offset+1)}–${N(Math.min(offset+30,r.total))} / ${N(r.total)}문항</span><div class="row"><button id="prev" ${offset===0?'disabled':''}>← 이전</button><button id="next" ${offset+30>=r.total?'disabled':''}>다음 →</button></div></div></section>`;
 $('bank-search').onsubmit=e=>{e.preventDefault();bankQuery=$('search').value;bankStatus=$('status').value;bankSource=$('source').value;offset=0;action(bankPage);};on('prev',()=>{offset=Math.max(0,offset-30);return bankPage();});on('next',()=>{offset+=30;return bankPage();});document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>action(()=>editQuestion(b.dataset.question),b));
}
async function editQuestion(id){const q=await api('/api/question?id='+encodeURIComponent(id)),evs=await api('/api/evidence');
 modal('문항 원문 대조 · 검수',`<div class="split"><section><p>${badge(q.reviewed?'검수 완료':'미검수 후보',q.reviewed?'green':'amber')} ${E(q.source_file||q.source_title)} · ${E(q.original_number)}번</p>${questionMarkup(q)}<p class="mini-stat">원문 위치: ${q.page?`PDF ${E((q.source_pages||[q.page]).join(", "))}페이지`:E(JSON.stringify(q.source_ref||{}))}</p>${q.review_notes?`<p class="notice">${E(q.review_notes)}</p>`:""}</section><form id="edit-form"><label>발문<textarea id="q-text" required>${E(q.text)}</textarea></label><label>지문<textarea id="q-passage">${E(q.passage||'')}</textarea></label><label>선택지 · 한 줄에 하나<textarea id="q-choices">${E((q.choices||[]).join('\n'))}</textarea></label><div class="split"><label>정답<input id="q-answer" value="${E(q.answer)}"></label><label>세부 개념 · 쉼표 구분<input id="q-concepts" value="${E((q.concepts||[]).join(', '))}"></label></div><label>해설<textarea id="q-explanation" rows="7">${E(q.explanation)}</textarea></label><div class="split"><label>학교<input id="q-school" value="${E(q.school||'')}"></label><label>난이도<select id="q-difficulty">${['미분류','하','중','상'].map(x=>`<option ${q.difficulty===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>요구 사고 유형 · 쉼표 구분<input id="q-types" value="${E((q.question_types||[]).join(', '))}"></label><label>풀이 판단 과정 · 쉼표 구분<input id="q-steps" value="${E((q.reasoning_steps||[]).join(', '))}"></label><label>연결할 프린트 근거<select id="q-evidence" multiple size="4">${evs.map(e=>`<option value="${E(e.id)}" ${q.evidence.some(v=>v.id===e.id)?'selected':''}>${E(e.title)} p.${e.page} · ${E(e.concept)}</option>`).join('')}</select></label><label class="check"><input type="checkbox" id="q-approved" ${q.reviewed?'checked':''}>원본·표·그림·정답·해설·분류를 확인했습니다</label><button class="primary">검수 내용 저장</button></form></div>`);
 const original=document.createElement('button');original.textContent='보관된 원본 파일 다운로드';original.onclick=()=>action(async()=>{if(window.researchDownloadSource)return window.researchDownloadSource(q.source_id);const r=await fetch('/source-file/'+q.source_id+'?token='+encodeURIComponent(token));if(!r.ok)throw Error((await r.json()).error);download((q.source_file||q.source_title).split(/[\\/]/).pop(),await r.blob());},original);$('dialog-body').prepend(original);
 $('edit-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('/api/question',{id:q.id,version:q.version,text:$('q-text').value,passage:$('q-passage').value,choices:$('q-choices').value.split('\n').filter(Boolean),answer:$('q-answer').value,explanation:$('q-explanation').value,concepts:$('q-concepts').value.split(',').map(x=>x.trim()).filter(Boolean),question_types:$('q-types').value.split(',').map(x=>x.trim()).filter(Boolean),reasoning_steps:$('q-steps').value.split(',').map(x=>x.trim()).filter(Boolean),school:$('q-school').value,difficulty:$('q-difficulty').value,evidence_ids:[...$('q-evidence').selectedOptions].map(x=>x.value),approved:$('q-approved').checked});$('dialog').close();toast('문항 검수 내용을 저장했습니다.');await navigate(page);},e.submitter);};
}
async function studentPage(){await getStudents();let a=null;if(sid)a=await api('/api/analysis?'+new URLSearchParams({student_id:sid}));currentAnalysis=a;
 $('main').innerHTML=heading('학생 오답 분석','김까까의 실제 답안과 학생이 기록한 이유를 근거로 살펴봅니다.')+`<section class="card"><div class="filters">${studentPicker()}<label>분석 기준<input value="시험·과제별 가장 최근 응시" readonly></label></div></section>`;
 wireStudent();if(!a){$('main').innerHTML+=empty('김까까 학생을 선택하세요','학생을 새로 등록하지 않습니다. 기존 학생 ID와 풀이 기록을 사용합니다.');return;}
 $('main').innerHTML+=stats([['연결된 응시 기록',a.history.length,'건','이전 답안이 남은 기록만 집계','◎'],['판정 가능한 답안',a.graded,'문항','빈 답안·서술형 자동 판정 제외','✓'],['현재 오답',a.wrong.length,'문항','시험별 최근 응시 기준','▤'],['학생 확인 필요',a.unlinked.length,'건','이름만 저장된 과거 응시','!']])+
 (a.unlinked.length?`<div class="notice"><strong>이름만 저장된 제출 ${a.unlinked.length}건이 있습니다.</strong>다른 학생의 기록이 섞이지 않도록 현재 분석에서 제외했습니다. 소유자를 확인하면 기존 학생 ID로 연결합니다. <button id="review-links">기록 확인 · 연결</button></div>`:'')+
 `<div class="split"><section class="card"><div class="card-head"><h2>개념별 오답 비율</h2>${badge('최근 응시 기준')}</div>${a.concepts.length?'<div class="chart-wrap"><canvas id="weak-chart" role="img" aria-label="개념별 오답 비율"></canvas></div>':empty('분석할 개념 기록이 없습니다','제출 기록을 연결하고 문항 개념을 분류하세요.')}</section><section class="card"><h2>복습할 프린트 · 보완점</h2>${a.concepts.filter(x=>x.wrong).slice(0,6).map(v=>`<div class="list-item"><div class="row"><b>${E(v.concept)}</b>${badge(v.wrong+'/'+v.graded+'문항 · '+v.rate+'%','amber')}</div>${v.evidence.length?v.evidence.map(e=>`<p>${E(e.title)} <b>p.${e.page}</b><br><small>${E(e.quote)}</small></p>`).join(''):'<p class="muted">프린트 근거 미연결 · 해당 개념의 페이지와 핵심 문장을 등록하세요.</p>'}<small>보완 순서: 근거 확인 → 개념 재진술 → 같은 개념의 검수 문항 풀이</small></div>`).join('')||empty('확인된 취약 개념이 없습니다')}</section></div><section class="card"><div class="card-head"><h2>실제 오답 · 학생이 남긴 이유</h2><button id="wrong-packet">원문 확인된 오답을 자료로 →</button></div>${a.wrong.map((w,i)=>`<article class="list-item"><div class="row"><h3>${E(w.exam)} · ${E(w.num)}번</h3>${badge(w.mapping.verified?'원문 대조 완료':'원문 확인 필요',w.mapping.verified?'green':'amber')}</div><p>${E(w.text||'기존 김까까 기록에 발문이 없습니다. 원문 대조가 필요합니다.')}</p><p><b>학생 답 ${E(w.answer)}</b> · 정답 ${E(w.correct)} · ${E(w.concepts.join(' / '))}</p><div class="reason">학생이 적은 이유: ${E(w.student_reason||'미입력')}</div>${w.note.error_type?`<p>교사 확인: ${E(w.note.error_type)} · ${E(w.note.note)}</p>`:''}<button data-map="${i}">동일 원문 연결 · 오답 유형 분류</button></article>`).join('')||empty('확인된 오답이 없습니다')}</section><section class="card"><h2>응시 기록</h2><div class="table-wrap"><table><thead><tr><th>시험·과제</th><th>제출일</th><th>오답 / 판정</th><th>제출 횟수</th></tr></thead><tbody>${a.history.map(r=>`<tr><td>${E(r.exam)}</td><td>${E((r.date||'').slice(0,10))}</td><td>${r.wrong} / ${r.graded}</td><td>${E(r.attempt_count||1)}회</td></tr>`).join('')}</tbody></table></div><small>재응시로 덮어쓴 이전 답안은 복원하거나 누적한 것으로 표시하지 않습니다.</small></section>`;
 wireStudent();if(a.concepts.length&&window.Chart){charts.push(new Chart($('weak-chart'),{type:'bar',data:{labels:a.concepts.slice(0,8).map(x=>x.concept),datasets:[{label:'오답 비율 %',data:a.concepts.slice(0,8).map(x=>x.rate),backgroundColor:'#98b286',borderRadius:5}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{max:100,min:0,grid:{color:'#eef1e9'}},y:{grid:{display:false}}}}}));}
 on('review-links',()=>reviewLinks(a));document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>action(()=>mapWrong(a.wrong[Number(b.dataset.map)]),b));
 on('wrong-packet',async()=>{const ws=a.wrong.filter(w=>w.mapping.verified&&w.mapping.question_id);if(!ws.length)throw Error('동일 원문 대조를 완료한 문항이 없습니다.');selected=[...new Map(ws.map(w=>[w.mapping.question_id,{type:'bank',id:w.mapping.question_id,label:w.exam+' '+w.num+'번'}])).values()];await navigate('packets');});
}
function reviewLinks(a){modal('과거 제출 기록 · 학생 소유자 확인',`<p>현재 학생: <strong>${E(a.student.name)}</strong> · 김까까 ID ${E(a.student.id)}</p><div class="notice">실제로 이 학생의 답안인지 확인한 기록만 선택하세요. 동명이인이 있으면 날짜와 시험을 추가로 대조하세요.</div>${a.unlinked.map(r=>`<label class="check"><input type="checkbox" name="link-record" value="${E(r.id)}">${E(r.exam)} · ${E(r.date)} ${r.same_name_count>1?' · ⚠ 동명이인 '+r.same_name_count+'명':''}</label>`).join('')}<button class="primary" id="confirm-links">선택한 기록을 이 학생 ID로 연결</button>`);on('confirm-links',async()=>{const ids=[...document.querySelectorAll('[name=link-record]:checked')].map(x=>x.value);if(!ids.length)throw Error('확인한 기록을 선택하세요.');await api('/api/link',{student_id:sid,response_ids:ids,confirmed:true});$('dialog').close();toast(ids.length+'개 기록을 기존 학생 ID에 연결했습니다.');await studentPage();});}
async function mapWrong(w){modal('오답 원문 연결 · 교사 확인',`<p><b>${E(w.exam)} · ${E(w.num)}번</b> / 학생 답 ${E(w.answer)} · 정답 ${E(w.correct)}</p><p class="question-text">${E(w.text||'발문 없음 · 원본 문항을 확인하세요.')}</p><div class="reason">학생 이유: ${E(w.student_reason||'미입력')}</div><label>검수 문항 검색<input id="map-query" placeholder="원문 발문 또는 출처"></label><button id="map-search">검색</button><label>동일 원문<select id="map-question"><option value="">미연결</option></select></label><div id="map-preview"></div><label class="check"><input type="checkbox" id="map-verified">발문·지문·선택지·번호를 대조했고 동일 원문입니다</label><label>세부 개념 · 쉼표 구분<input id="map-concepts" value="${E(w.concepts.join(', '))}"></label><label>교사 확인 오답 원인<select id="map-reason">${['미확인','개념 부족','프린트 암기 부족','적용 실패','선지 판단 오류','지문 근거 누락','추론 실패','반복 실수'].map(x=>`<option ${w.note.error_type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>확인 근거<textarea id="map-note">${E(w.note.note||'')}</textarea></label><button class="primary" id="map-save">연결·분류 저장</button>`);
 async function search(){const r=await api('/api/questions?'+new URLSearchParams({q:$('map-query').value,status:'approved'}));$('map-question').innerHTML='<option value="">미연결</option>'+r.items.map(q=>`<option value="${E(q.id)}">${E(q.source_title)} · ${E(q.original_number)}번 · ${E(q.text.slice(0,45))}</option>`).join('');}
 on('map-search',search);$('map-question').onchange=()=>action(async()=>{$('map-verified').checked=false;const id=$('map-question').value;if(!id){$('map-preview').innerHTML='';return;}const q=await api('/api/question?id='+id);$('map-preview').innerHTML=questionMarkup(q);$('map-concepts').value=(q.concepts||[]).join(', ');});
 on('map-save',async()=>{await api('/api/mapping',{student_id:sid,response_id:w.response_id,question_index:w.question_index,question_id:$('map-question').value,verified:$('map-verified').checked,concepts:$('map-concepts').value.split(',').map(x=>x.trim()).filter(Boolean),error_type:$('map-reason').value==='미확인'?'':$('map-reason').value,note:$('map-note').value});$('dialog').close();toast('오답 분류를 저장했습니다.');await studentPage();});await search();
}
async function sourcePage(){summary=await api('/api/summary');const es=await api('/api/evidence');
 $('main').innerHTML=heading('원본과 학습 근거','자료 파일·문항 적재·프린트 근거를 구분해 관리합니다.',`<button class="primary" id="add-source">＋ 자료 보관</button>`)+
 `<div class="tabs"><button id="add-evidence">＋ 프린트 근거·명제 등록</button><button id="import-json">문항 JSON 가져오기</button></div><section class="card"><div class="card-head"><h2>원본별 실제 적재 현황</h2>${badge(summary.sources.length+'개 원본')}</div><div class="table-wrap"><table><thead><tr><th>자료명</th><th>유형 / 학교</th><th>문항 후보</th><th>검수 완료</th><th>보관 크기</th></tr></thead><tbody>${summary.sources.map(s=>`<tr><td class="source-title">${E(s.title)}</td><td>${E(s.kind)}<br><small>${E(s.school||'학교 미지정')}</small></td><td>${N(s.total)}</td><td>${N(s.approved)}<div class="progress"><i style="width:${s.total?s.approved/s.total*100:0}%"></i></div></td><td>${(s.bytes/1024/1024).toFixed(1)} MB</td></tr>`).join('')}</tbody></table></div></section><section class="card"><h2>프린트 페이지 · 핵심명제</h2>${es.map(e=>`<article class="list-item"><div class="row"><b>${E(e.title)} · p.${e.page}</b>${badge(e.concept,'green')}${badge(e.approved?'검수 완료':'미검수',e.approved?'green':'amber')}</div><p>${E(e.quote)}</p><small>핵심명제: ${E(e.statement)}${e.blank_answer?' · 빈칸 정답: '+E(e.blank_answer):''}</small></article>`).join('')||empty('등록된 프린트 근거가 없습니다','원본 자료를 고르고 페이지·근거 문장·검수한 핵심명제를 등록하세요.')}</section>`;
 on('add-source',sourceForm);on('add-evidence',evidenceForm);on('import-json',importForm);
}
function sourceForm(){modal('원본 자료 보관',`<form id="source-form"><label>자료명<input id="s-title" required></label><div class="split"><label>종류<select id="s-kind">${['학교 프린트','교사 필기','학교 기출','내신 기출','모의고사','클리닉','과제','문법 기출'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>학교<input id="s-school"></label></div><label>원본 파일 · 40MB 이하<input type="file" id="s-file" accept=".pdf,.hwp,.hwpx,.txt,.json"></label><div class="notice">원본 파일 보관 후 문항 JSON을 가져오거나 문항을 직접 등록하세요. 파일 업로드만으로 문항 적재 완료로 표시하지 않습니다.</div><button class="primary">자료 보관</button></form>`);$('source-form').onsubmit=e=>{e.preventDefault();action(async()=>{const f=$('s-file').files[0];let data='';if(f){if(f.size>40*1024*1024)throw Error('40MB 이하 파일을 선택하세요.');const b=new Uint8Array(await f.arrayBuffer());let str='';for(let i=0;i<b.length;i+=8192)str+=String.fromCharCode(...b.subarray(i,i+8192));data=btoa(str);}const r=await api('/api/source',{title:$('s-title').value,kind:$('s-kind').value,school:$('s-school').value,filename:f?.name,data});$('dialog').close();toast(r.duplicate?'동일 파일이 이미 보관되어 있습니다.':'자료를 보관했습니다.');await sourcePage();},e.submitter);};}
function evidenceForm(){modal('프린트 근거 · 핵심명제 등록',`<form id="evidence-form"><label>원본 자료<select id="e-source" required>${sourceOptions()}</select></label><div class="split"><label>인쇄된 페이지 번호<input type="number" min="1" value="1" id="e-page" required></label><label>세부 개념<input id="e-concept" required placeholder="예: 객체 높임 선어말어미"></label></div><label>프린트의 실제 근거 문장<textarea id="e-quote" required></textarea></label><label>참인 핵심명제 · 조건을 생략하지 마세요<textarea id="e-statement" required></textarea></label><label>빈칸으로 바꿀 정답 · 명제에 포함된 어구<input id="e-blank"></label><label class="check"><input id="e-approved" type="checkbox" required>원문과 대조했고 핵심명제의 조건·정확성을 확인했습니다</label><p class="muted">같은 핵심명제는 OX와 빈칸 사이에서도 중복 출제를 막습니다. 동의 표현도 기존 명제를 확인해 하나로 등록하세요.</p><button class="primary">근거 저장</button></form>`);$('evidence-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('/api/evidence',{source_id:$('e-source').value,page:Number($('e-page').value),quote:$('e-quote').value,concept:$('e-concept').value,statement:$('e-statement').value,blank_answer:$('e-blank').value,approved:$('e-approved').checked});$('dialog').close();toast('검수 근거와 핵심명제를 저장했습니다.');await sourcePage();},e.submitter);};}
function importForm(){modal('문항 JSON 가져오기 · 직접 등록',`<form id="import-form"><label>소속 원본<select id="i-source">${sourceOptions()}</select></label><label>문항 JSON 파일<input id="i-file" type="file" accept=".json"></label><label>또는 문항 직접 입력 · JSON 배열<textarea id="i-json" rows="12" placeholder='[{"text":"발문","choices":["선택지1","선택지2"],"answer":"1","explanation":"근거 해설","concepts":["세부개념"],"original_number":"1"}]'></textarea></label><p class="muted">한 번에 500문항 이하. 기존 원문 위치·문항 내용이 같으면 중복으로 제외하며, 모든 문항은 미검수 상태로 시작합니다.</p><button class="primary">검수 대기 문항으로 저장</button></form>`);$('import-form').onsubmit=e=>{e.preventDefault();action(async()=>{const f=$('i-file').files[0];let qs=JSON.parse(f?await f.text():$('i-json').value);if(!Array.isArray(qs))qs=qs.questions;const r=await api('/api/import',{source_id:$('i-source').value,questions:qs});$('dialog').close();toast(`${r.added}문항 저장 · 중복/빈 문항 ${r.skipped}개 제외`);await sourcePage();},e.submitter);};}
async function dailyPage(){await getStudents();summary=await api('/api/summary');const qs=sid?await api('/api/generated?student_id='+encodeURIComponent(sid)):[];
 $('main').innerHTML=heading('오늘의 복습','학생의 취약 개념과 검수한 핵심명제로 새로운 복습을 준비합니다.')+`<section class="card"><div class="filters">${studentPicker()}<button id="generate" class="primary" ${!sid?'disabled':''}>오늘의 OX·빈칸 생성</button><button id="variant" ${!sid?'disabled':''}>AI 변형문항 만들기</button></div><label class="check"><input id="schedule" type="checkbox" ${summary.scheduled?'checked':''}>이 PC에서 연구소가 실행 중일 때 하루 한 번 자동 생성</label><small>한국 시간 기준 학생별 하루 1회 · 문항·핵심명제 중복 차단 · 자료 부족 시 생성을 중단합니다. 규칙 생성은 검수한 참 명제로 OX(O)·빈칸을 만들며, AI 변형은 별도로 요청합니다.</small></section>`+
 `<section class="card"><div class="card-head"><h2>${sid?E(studentName())+'의 생성 이력':'생성문항 검토'}</h2>${badge(qs.length+'문항')}</div>${qs.map(q=>`<article class="list-item"><div class="row">${badge(q.kind==='blank'?'빈칸':q.kind==='ox'?'OX':'AI 변형','blue')}${badge(q.status==='approved'?'승인':q.status==='rejected'?'반려':'검토 대기',q.status==='approved'?'green':'amber')}<small>${E(q.created_at.slice(0,10))} · ${E(q.body.source_title)} p.${q.body.page}</small></div><p class="question-text">${E(q.body.text)}</p>${q.body.choices?.length?'<ol>'+q.body.choices.map(v=>`<li>${E(v)}</li>`).join('')+'</ol>':''}<p>정답 <b>${E(q.body.answer)}</b></p><details><summary>근거·해설</summary><div class="passage">${E(q.body.explanation)}</div></details><div class="row">${q.status==='pending'?`<button data-approve="${q.id}" class="primary">교사 승인</button><button data-reject="${q.id}">반려</button>`:''}${q.status==='approved'?`<button data-select-generated="${q.id}">자료에 담기</button>`:''}</div></article>`).join('')||empty('아직 생성한 문항이 없습니다','취약 개념과 연결된 프린트 근거를 등록하면 생성할 수 있습니다.')}</section><section class="card"><h2>하루 생성 실행 기록</h2>${summary.runs.filter(r=>!sid||r.student_id===sid).map(r=>`<div class="source-row"><span>${E(r.day)} · ${E(students.find(s=>String(s.id)===r.student_id)?.name||r.student_id)}</span><span>${E(r.detail)}</span></div>`).join('')||'<p class="muted">실행 기록이 없습니다.</p>'}</section>`;
 wireStudent();on('generate',async()=>{const r=await api('/api/generate',{student_id:sid});toast((r.reused?'오늘 이미 실행했습니다. ':'')+r.detail);await dailyPage();});$('schedule').onchange=()=>action(async()=>{await api('/api/schedule',{enabled:$('schedule').checked});toast('자동 생성 설정을 저장했습니다.');});on('variant',variantForm);
 document.querySelectorAll('[data-approve],[data-reject]').forEach(b=>b.onclick=()=>action(async()=>{await api('/api/generated/review',{id:b.dataset.approve||b.dataset.reject,status:b.dataset.approve?'approved':'rejected'});await dailyPage();},b));
 document.querySelectorAll('[data-select-generated]').forEach(b=>b.onclick=()=>{const q=qs.find(q=>q.id===b.dataset.selectGenerated);addSelection({type:'generated',id:q.id,label:q.body.text});});
}
async function variantForm(){const r=await api('/api/recommend?student_id='+sid);if(!r.length)throw Error('먼저 오답 개념과 일치하는 검수 문항을 준비하세요.');modal('AI 변형문항 · 교사 검수용',`<div class="notice">기존 김까까 AI 기능을 사용합니다. 학생 이름·답안은 전송하지 않으며, 검수 문항과 프린트 근거만 전달합니다. AI 응답은 승인 대기로 저장됩니다.</div><label>원본 문항<select id="v-question"><option value="">문항 선택</option>${r.map(x=>`<option value="${x.question.id}">${E(x.question.text)}</option>`).join('')}</select></label><label>연결된 검수 근거<select id="v-evidence"></select></label><button id="v-generate" class="primary">변형 초안 생성</button>`);$('v-question').onchange=()=>action(async()=>{if(!$('v-question').value)return;const q=await api('/api/question?id='+$('v-question').value);$('v-evidence').innerHTML=q.evidence.filter(e=>e.approved).map(e=>`<option value="${e.id}">${E(e.title)} p.${e.page} · ${E(e.concept)}</option>`).join('');});on('v-generate',async()=>{if(!$('v-evidence').value)throw Error('문항에 연결된 검수 근거가 없습니다.');toast('근거를 바탕으로 변형문항을 만들고 있습니다…');await api('/api/variant',{student_id:sid,question_id:$('v-question').value,evidence_id:$('v-evidence').value});$('dialog').close();toast('변형 초안을 저장했습니다. 정답과 해설을 검수하세요.');await dailyPage();});}
function addSelection(q){if(!sid){toast('학생을 먼저 선택하세요.');return;}if(!selected.some(x=>x.id===q.id&&x.type===q.type))selected.push(q);toast('개인별 자료에 '+selected.length+'문항을 담았습니다.');}
async function packetPage(){await getStudents();const packets=sid?await api('/api/packets?student_id='+sid):[],rec=sid?await api('/api/recommend?student_id='+sid):[];
 $('main').innerHTML=heading('개인별 자료','검수한 문항을 모아 주간 클리닉과 과제를 만듭니다.')+`<section class="card"><div class="filters">${studentPicker()}</div></section><div class="split"><section class="card"><h2>이번 주 맞춤 오답정리</h2><label>자료 제목<input id="packet-title" value="${E(studentName())} · ${new Date().toLocaleDateString('ko-KR')} 주간 오답정리"></label><label>분석 요약 · 복습할 프린트 안내<textarea id="packet-summary" rows="4" placeholder="확인된 취약 개념과 복습할 프린트 위치를 적어 주세요."></textarea></label><div id="selected-items">${selected.map((x,i)=>`<div class="source-row"><span>${i+1}. ${E(x.label.slice(0,80))}</span><button data-remove="${i}">제외</button></div>`).join('')||empty('아직 선정한 문항이 없습니다','원문 확인된 실제 오답, 유사문항, 승인한 복습문항을 담아 주세요.')}</div><button class="primary" id="save-packet" ${!sid||!selected.length?'disabled':''}>${selected.length}문항으로 자료 저장</button></section><section class="card"><h2>취약 개념 기반 유사문항</h2>${rec.map(r=>`<div class="list-item"><p>${E(r.question.text)}</p><small>일치 개념: ${E(r.matched.join(' · '))} / ${E(r.question.source_title)}</small><div class="row"><button data-rec="${r.question.id}">자료에 담기</button><button data-inspect="${r.question.id}">원문 보기</button></div></div>`).join('')||empty('추천할 검수 문항이 없습니다','오답 세부 개념과 같은 개념의 검수 문항이 필요합니다.')}</section></div><section class="card"><div class="card-head"><h2>저장한 자료</h2>${badge(packets.length+'개')}</div>${packets.map(p=>`<div class="list-item"><div class="row"><h3>${E(p.title)}</h3>${badge(p.status==='approved'?'교사 승인 완료':'초안',p.status==='approved'?'green':'amber')}</div><p>${p.body.items.length}문항 · ${E(p.created_at.slice(0,10))}</p><div class="row"><button data-preview="${p.id}">미리보기 · 인쇄</button><button data-render="${p.id}">서로국어 한글·PDF 제작</button>${p.status!=='approved'?`<button data-packet-approve="${p.id}">자료 확인 · 승인</button>`:`<button data-export="${p.id}">김까까 연동용 내려받기</button>`}${p.files.map(f=>`<button data-file-packet="${p.id}" data-file="${E(f)}">${E(f.split('.').pop().toUpperCase())} 다운로드</button>`).join('')}</div>${p.files.length?'<small>자동 제작 파일은 지면을 확인한 뒤 승인하세요.</small>':''}</div>`).join('')||empty('저장된 개인별 자료가 없습니다')}</section><div class="notice"><strong>김까까 공유 상태: 연동용 내보내기 가능 · 학생 화면 자동 게시 미연결</strong>기존 학생 ID와 승인 자료를 묶어 내보냅니다. 현재 운영 DB에 문제은행용 테이블이 없어 자동 게시 기능은 아직 연결하지 않았습니다.</div>`;
 wireStudent();document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selected.splice(Number(b.dataset.remove),1);action(packetPage);});document.querySelectorAll('[data-rec]').forEach(b=>b.onclick=()=>{const q=rec.find(x=>x.question.id===b.dataset.rec).question;addSelection({type:'bank',id:q.id,label:q.text});action(packetPage);});document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>action(()=>editQuestion(b.dataset.inspect),b));
 on('save-packet',async()=>{await api('/api/packet',{student_id:sid,title:$('packet-title').value,summary:$('packet-summary').value,items:selected});selected=[];toast('자료 초안을 저장했습니다.');await packetPage();});
 document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>action(()=>previewPacket(b.dataset.preview),b));document.querySelectorAll('[data-render]').forEach(b=>b.onclick=()=>action(async()=>{toast('서로국어 양식으로 한글과 PDF를 제작합니다. 잠시 기다려 주세요.');await api('/api/render',{id:b.dataset.render});toast('한글·PDF를 제작했습니다. 지면을 확인한 뒤 승인하세요.');await packetPage();},b));
 document.querySelectorAll('[data-packet-approve]').forEach(b=>b.onclick=()=>action(()=>previewPacket(b.dataset.packetApprove,true),b));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>action(async()=>{const data=await api('/api/export',{id:b.dataset.export});download('김까까-오답정리-'+data.external_packet_id+'.json',JSON.stringify(data,null,2));},b));document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>action(async()=>{const r=await fetch('/download/'+b.dataset.filePacket+'/'+encodeURIComponent(b.dataset.file)+'?token='+encodeURIComponent(token));if(!r.ok)throw Error('다운로드할 수 없습니다.');download(b.dataset.file,await r.blob());},b));
}
function download(name,data){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function previewPacket(id,approve=false){const p=await api('/api/packet?id='+id),b=p.body;
 modal('개인별 자료 미리보기',`<div class="row no-print"><button id="print-paper" class="primary">인쇄 · PDF로 저장</button>${approve?'<label class="check"><input type="checkbox" id="packet-checked">문항·정답·해설·학생·출력 지면을 확인했습니다</label><button id="approve-paper">승인 완료</button>':''}</div><div class="paper"><p class="eyebrow">서로국어 · 오답연구소</p><h1>${E(b.title)}</h1><p style="text-align:center">${E(b.student_name)} · ${b.items.length}문항</p><div class="passage">${E(b.summary)}</div>${b.items.map((q,i)=>`<section class="q"><h3>${i+1}. ${E(q.text)}</h3>${questionMarkup({...q,text:''},false)}<small>${E(q.source_title)} ${q.page?'· p.'+q.page:''}</small></section>`).join('')}<section class="answers"><h2>정답과 해설</h2>${b.items.map((q,i)=>`<section class="q"><h3>${i+1}. 정답 ${E(q.answer)}</h3>${E(q.explanation)}</section>`).join('')}</section></div>`);
 on('print-paper',()=>window.print());on('approve-paper',async()=>{if(!$('packet-checked').checked)throw Error('자료와 지면을 확인한 뒤 체크하세요.');await api('/api/packet/approve',{id,confirmed:true});$('dialog').close();toast('자료를 승인했습니다.');await packetPage();});
}
$('close-dialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('click',e=>{if(e.target===$('dialog'))$('dialog').close();});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>action(()=>navigate(b.dataset.page),b));$('refresh').onclick=e=>action(async()=>{toast('김까까의 최신 학생·답안 기록을 확인합니다.');await api('/api/refresh',{});students=[];await navigate(page);toast('김까까 DB에서 최신 기록을 불러왔습니다.');},e.currentTarget);Promise.resolve(window.researchReady).then(()=>navigate('home'));
