async function inputStatusPage(){
 const d=await api('/api/input-status'),tot=d.items.reduce((a,s)=>({wrong:a.wrong+s.wrong,reasons:a.reasons+s.reasons}),{wrong:0,reasons:0});
 $('main').innerHTML=heading('학생 오답 입력 현황','국어왕의 현재 답안·오답 이유를 직접 확인합니다.',`<button class="primary" id="input-refresh">최신 입력 다시 확인</button>`)+
 stats([['학생',d.items.length,'명','기존 학생 ID'],['제출 기록',d.responses,'건','원본 제출 기록 전체'],['최신 응시 오답',tot.wrong,'문항','시험별 최근 응시 기준'],['오답 이유 작성',tot.reasons,'문항','최신 오답 중 작성한 이유']])+
 `<section class="card"><p role="status">최신 확인: ${E(new Date(d.checked_at).toLocaleString('ko-KR'))}</p><p class="notice">${d.unlinked_responses?`학생 ID가 연결되지 않은 제출 ${N(d.unlinked_responses)}건은 학생별 집계에서 제외했습니다. `:''}미응답·자동 채점 불가 문항은 오답으로 단정하지 않습니다. 마지막 제출 시각은 오답 이유의 수정 시각과 다를 수 있습니다. 이미 만든 자료는 자동으로 덮어쓰지 않습니다.</p><div class="table-wrap"><table><thead><tr><th>학생</th><th>최근 제출</th><th>응시 시험</th><th>최신 오답</th><th>이유 작성 / 미작성</th><th>미응답·채점 미확인</th><th></th></tr></thead><tbody>${d.items.map(s=>`<tr><td>${E(s.name)}<br><small>${E(s.school)} · ${E(s.status||'')}</small></td><td>${s.last_submitted_at?E(new Date(s.last_submitted_at).toLocaleString('ko-KR')):'제출 없음'}</td><td>${N(s.submissions)}</td><td>${N(s.wrong)}</td><td>${N(s.reasons)} / ${N(s.wrong-s.reasons)}</td><td>${N(s.ungraded)}</td><td><button data-input-student="${E(s.id)}">최신 오답 분석</button></td></tr>`).join('')}</tbody></table></div></section>`;
 on('input-refresh',inputStatusPage);document.querySelectorAll('[data-input-student]').forEach(b=>b.onclick=()=>action(async()=>{sid=b.dataset.inputStudent;students=[];selected=[];await navigate('students');},b));
}
const inputNavigate=navigate;navigate=async function(name){if(name!=='input-status')return inputNavigate(name);page=name;charts.forEach(c=>c.destroy());charts=[];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$('breadcrumb').textContent='학생 오답 입력 현황';try{await inputStatusPage();}catch(e){$('main').innerHTML=empty('최신 입력 현황을 불러오지 못했습니다',e.message);}};
const inputNav=document.createElement('button');inputNav.dataset.page='input-status';inputNav.textContent='↻ 학생 오답 입력 현황';inputNav.onclick=()=>action(()=>navigate('input-status'),inputNav);document.querySelector('nav').append(inputNav);
