(function(){
 'use strict';const BASE='https://zniwzwanlvvmzkkcmikh.supabase.co',KEY='sb_publishable_IbfVcXs5TmXfumrnK4Somg_7MzygCdh';let auth=null;
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function rpc(action,payload={}){const r=await fetch(BASE+'/rest/v1/rpc/odap_rpc',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({p_id:auth.id,p_password:auth.pw,p_role:'student',p_action:action,p_payload:payload})});const d=await r.json();if(!r.ok)throw Error(d.message||'자료를 불러오지 못했습니다.');return d;}
 async function login(credentials){auth={...credentials,role:'student'};try{const profile=await rpc('profile'),packets=await rpc('student_packets');document.getElementById('student-title').textContent=profile.name+'의 오답정리';document.getElementById('student-login').hidden=true;document.getElementById('student-packets').innerHTML=packets.map(p=>`<section class="card"><h2>${e(p.title)}</h2><p class="passage">${e(p.body.summary)}</p>${(p.files||[]).filter(f=>f.kind==='pdf').map(f=>`<button data-path="${e(f.path)}" data-name="${e(f.name)}">PDF 내려받기</button>`).join('')}<details><summary>복습 문항 펼치기</summary>${(p.body.items||[]).map((q,i)=>`<article class="list-item"><h3>${i+1}. ${e(q.text)}</h3>${q.passage?`<p class="passage">${e(q.passage)}</p>`:''}<div class="question-images">${(q.images||[]).filter(x=>/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(x.data||'')).map(x=>`<img src="${x.data}" alt="${e(x.alt||'원본 그림')}">`).join('')}</div><ol>${(q.choices||[]).map(c=>`<li>${e(c)}</li>`).join('')}</ol><details><summary>정답·해설 확인</summary><b>정답 ${e(q.answer)}</b><p class="passage">${e(q.explanation)}</p></details></article>`).join('')}</details></section>`).join('')||'<div class="empty"><strong>아직 공개된 자료가 없어요.</strong>선생님이 자료를 공개하면 여기에 표시돼요.</div>';
 document.querySelectorAll('[data-path]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await fetch(BASE+'/functions/v1/odap-assets',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({credentials:auth,action:'download',path:b.dataset.path,filename:b.dataset.name})});const d=await r.json();if(!r.ok)throw Error(d.error||'다운로드 실패');const file=await fetch(d.url);if(!file.ok)throw Error('파일 다운로드 실패');const u=URL.createObjectURL(await file.blob()),a=document.createElement('a');a.href=u;a.download=b.dataset.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(err){document.getElementById('student-message').textContent=err.message;}finally{b.disabled=false;}});
 }catch(err){auth=null;document.getElementById('student-login').hidden=false;document.getElementById('student-message').textContent=err.message;}}
 document.querySelector('form').onsubmit=ev=>{ev.preventDefault();login({id:ev.target.elements.id.value.trim(),pw:ev.target.elements.pw.value});};
 const nonce=new URLSearchParams(location.search).get('embedded');if(nonce&&parent!==window){document.getElementById('student-login').hidden=true;const receive=ev=>{if(ev.origin!==location.origin||ev.source!==parent||ev.data?.type!=='odap-login'||ev.data.nonce!==nonce||ev.data.role!=='student')return;window.removeEventListener('message',receive);login(ev.data);};window.addEventListener('message',receive);parent.postMessage({type:'odap-ready',nonce},location.origin);}
 window.addEventListener('pagehide',()=>{auth=null;});
})();
