const fs=require('node:fs'),assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create table users(id text primary key,name text,role text,status text,school_id text);create table qa_schools(id text primary key,name text);create table exams(id text primary key,name text,category text,questions jsonb);create table exam_responses(id text primary key,exam_id text,student_name text,answers jsonb,score integer,submitted_at timestamptz,attempt_count integer);create function authenticate_user(text,text,text) returns jsonb language sql as $$select to_jsonb(u) from users u where id=$1 and $2='test-only' and role=$3$$;insert into users values('teacher','Teacher','teacher','active',null),('s1','Same','student','active','school'),('s2','Same','student','active','school'),('s3','Unique','student','active','school');insert into qa_schools values('school','학교');insert into exams values('exam','시험','homework','[{"text":"발문","answer":"1","concepts":["음운"]}]');insert into exam_responses values('r1','exam','Same','{"0":"2"}',0,now(),1),('r3','exam','Unique','{"0":"2"}',0,now(),1);`);
await db.exec(fs.readFileSync('supabase/odap/migration.sql','utf8'));
await db.exec(fs.readFileSync('supabase/odap/linked-data.sql','utf8'));
await db.exec(fs.readFileSync('supabase/odap/fast-sync.sql','utf8'));
await db.exec(fs.readFileSync('supabase/odap/fast-search.sql','utf8')); 
const rpc=async(action,payload={},id='teacher',role='teacher',pw='test-only')=>(await db.query('select odap_rpc($1,$2,$3,$4,$5) result',[id,pw,role,action,JSON.stringify(payload)])).rows[0].result;
const revision=await rpc('GET /api/sync');assert.equal(typeof revision,'string');
assert.equal((await rpc('GET /api/records',{student_id:'s3'})).responses.length,1);
await db.exec("update exams set name='시험 수정' where id='exam'");assert.equal((await db.query("select count(*)::int n from pg_trigger where tgname='odap_revision_changed' and tgrelid in ('users'::regclass,'exams'::regclass,'exam_responses'::regclass)")).rows[0].n,0);
await db.exec("create or replace function odap_touch_revision() returns trigger language plpgsql as $$begin raise exception 'simulated Odap outage';end$$;update exams set name='still usable' where id='exam';");
assert.equal((await db.query("select name from exams where id='exam'")).rows[0].name,'still usable');
await db.exec(fs.readFileSync('supabase/odap/fast-sync.sql','utf8'));
assert.match(await rpc('GET /api/sync'),/^[a-f0-9-]+:\d+$/);
const linked=async(table,id='teacher',pw='test-only')=>(await db.query('select odap_linked_data($1,$2,$3) result',[id,pw,table])).rows[0].result;
assert.equal((await linked('exams')).total,1);await assert.rejects(()=>linked('users'));await assert.rejects(()=>linked('exams','s1'));
await assert.rejects(()=>rpc('GET /api/students',{},'teacher','teacher','bad'));await assert.rejects(()=>rpc('GET /api/students',{},'s1','student'));
let s=await rpc('GET /api/summary');assert.equal(s.connection.students,3);assert.equal((await db.query("select student_id from exam_responses where id='r1'")).rows[0].student_id,null);assert.equal((await db.query("select student_id from exam_responses where id='r3'")).rows[0].student_id,'s3');
const src=await rpc('POST /api/source',{title:'원본',kind:'학교 프린트',school:'학교'});assert.ok(src.id);
let added=await rpc('POST /api/import',{source_id:src.id,questions:[{text:'음운의 뜻은?',choices:['가','나'],answer:'1',explanation:'뜻 구별',concepts:['음운'],original_number:'1'}]});assert.equal(added.added,1);
assert.equal((await rpc('GET /api/questions',{q:'음운'})).total,1);assert.equal((await rpc('GET /api/questions',{q:'없는검색어'})).total,0);
const bank=await rpc('GET /api/questions');assert.equal(bank.total,1);let q=await rpc('GET /api/question',{id:bank.items[0].id});
await assert.rejects(()=>rpc('POST /api/packet',{student_id:'s3',items:[{type:'bank',id:q.id}]}));
await rpc('POST /api/question',{...q,approved:true,evidence_ids:[]});q=await rpc('GET /api/question',{id:q.id});assert.equal(q.reviewed,true);
const ev=await rpc('POST /api/evidence',{source_id:src.id,page:2,quote:'음운은 뜻을 구별한다.',concept:'음운',statement:'음운은 뜻을 구별한다.',blank_answer:'음운',approved:true});
await rpc('POST /api/question',{...q,approved:true,evidence_ids:[ev.id]});q=await rpc('GET /api/question',{id:q.id});assert.equal(q.evidence.length,1);
let run=await rpc('POST /api/generate',{student_id:'s3'});assert.equal(run.count,1);assert.equal((await rpc('POST /api/generate',{student_id:'s3'})).reused,true);
const gen=(await rpc('GET /api/generated',{student_id:'s3'}))[0];await assert.rejects(()=>rpc('POST /api/packet',{student_id:'s3',items:[{type:'generated',id:gen.id}]}));await rpc('POST /api/generated/review',{id:gen.id,status:'approved'});await assert.rejects(()=>rpc('POST /api/packet',{student_id:'s1',items:[{type:'generated',id:gen.id}]}));
const p=await rpc('POST /api/packet',{student_id:'s3',title:'검증',items:[{type:'bank',id:q.id}]});const meta=await rpc('GET /api/packet',{id:p.id,metadata_only:true});assert.equal(meta.id,p.id);assert.equal(meta.body,undefined);assert.ok((await rpc('GET /api/packet',{id:p.id})).body);await assert.rejects(()=>rpc('POST /api/publish',{...p,confirmed:true}));await rpc('POST /api/packet/approve',{...p,confirmed:true});await rpc('POST /api/publish',{...p,confirmed:true});assert.equal((await rpc('student_packets',{},'s3','student')).length,1);assert.equal((await rpc('student_packets',{},'s1','student')).length,0);
await rpc('POST /api/link',{student_id:'s1',response_ids:['r1'],confirmed:true});await assert.rejects(()=>rpc('POST /api/link',{student_id:'s2',response_ids:['r1'],confirmed:true}));
await db.exec("update exam_responses set answers='{\"0\":\"1\"}' where id='r3'");assert.equal((await db.query('select count(*)::int n from odap_attempts')).rows[0].n,1);
await db.exec("alter table exam_responses alter column id set default gen_random_uuid()::text;alter table exam_responses add column regrade_approved boolean default false;alter table exam_responses add column regrade_requested boolean default false;insert into exams values('exam2','시험2','homework','[]');");
await db.exec(fs.readFileSync('supabase/odap/identity-save.sql','utf8'));
const submit=async(id,payload,pw='test-only',role='student')=>(await db.query('select odap_save_response($1,$2,$3,$4) result',[id,pw,role,JSON.stringify(payload)])).rows[0].result;
await assert.rejects(()=>submit('s3',{exam_id:'exam2',answers:{}},'bad'));
const submitted=await submit('s3',{exam_id:'exam2',student_id:'s1',student_name:'Same',answers:{0:'1'}});assert.equal(submitted.student_id,'s3');assert.equal(submitted.student_name,'Unique');assert.equal(submitted.attempt_count,1);
await assert.rejects(()=>submit('s3',{exam_id:'exam2',answers:{0:'2'}}));
await db.exec("update exam_responses set regrade_approved=true where exam_id='exam2'");
const retake=await submit('s3',{exam_id:'exam2',answers:{0:'2'}});assert.equal(retake.attempt_count,2);assert.equal(retake.regrade_approved,false);assert.equal((await db.query('select count(*)::int n from odap_attempts')).rows[0].n,2);
await assert.rejects(()=>submit('s2',{exam_id:'exam',answers:{0:'1'}}));
await db.exec('set role anon');await assert.rejects(()=>db.query('select * from odap_questions'));await db.exec('reset role');
console.log('PASS: cloud migration, legacy identity backfill, auth, student isolation, source/import/review, evidence, daily dedup, approval, publishing, attempt history, RLS');await db.close();})().catch(e=>{console.error(e);process.exitCode=1});
